GET http://localhost:3001/api/notes/ HTTP/1.1

### 

POST http://localhost:3001/api/notes/ HTTP/1.1
Content-Type: application/json

{
    "content" : "Momento para programar",
    "important": true
}

###

DELETE http://localhost:3001/api/notes/669bd9be8dfdab3cd035ee7c HTTP/1.1

###

PUT http://localhost:3001/api/notes/66a03c38554a3229f480ad42 HTTP/1.1
Content-Type: application/json

{
    "content" : "Escenario Frontend",
    "important": true
}